// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xTrRmXMf-Ff6Hr8lK0Lqq9cgsZ6kIPo',
    appId: '1:638244808472:web:51c0add563b5e8f49a606d',
    messagingSenderId: '638244808472',
    projectId: 'flutteremail-1adc4',
    authDomain: 'flutteremail-1adc4.firebaseapp.com',
    storageBucket: 'flutteremail-1adc4.appspot.com',
    measurementId: 'G-LGEWGDMFD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlf-ZEnKpVnY9fCejuOhijnHSdRZ0D1Po',
    appId: '1:638244808472:android:92d6544afa86645c9a606d',
    messagingSenderId: '638244808472',
    projectId: 'flutteremail-1adc4',
    storageBucket: 'flutteremail-1adc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiO5juG9kog6mTUCZ5ll8AAsEm8Dnbm6A',
    appId: '1:638244808472:ios:72f9ad62135427f09a606d',
    messagingSenderId: '638244808472',
    projectId: 'flutteremail-1adc4',
    storageBucket: 'flutteremail-1adc4.appspot.com',
    androidClientId: '638244808472-4liba6n7ro8igekk3q1ln6972cl67crk.apps.googleusercontent.com',
    iosClientId: '638244808472-7jaiuu27uscfhc8t47h4teablvr2tt1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kriscentSocail',
  );

}